import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alpha Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.imagewrap}>
        <img className={styles.myImg} src="/img1.jpg" alt='alpha coder' width={237} height={158} />
        </div>
        <h1 className={styles.title}>
         Alpha Coder
        </h1>
        <p className={styles.description}>
          A blog for coders by a Alpha Coder which will resolve all the issues related to the coding and it will guide you to learn coding in correct way. It will help all the coders community from beginners to advanced ones.
        </p>

        <div className="blogs">
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className={styles.blogItem}>
            <h3 className={styles.h3}>How to learn Javascript in 2022</h3>
            <p className={styles.para}>Javascript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3 className={styles.h3}>How to learn NextJs in 2022</h3>
            <p className={styles.para}>NextJs is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3 className={styles.h3}>How to learn Flask in 2022</h3>
            <p className={styles.para}>Flask is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
